spring:
  application:
    name: spring-boot4
  mvc:
    apiversion:
      default: 1.0.0
      use:
        header: X-Version
  datasource:
    url: jdbc:mysql://localhost/springboot4?createDatabaseIfNotExist=true&rewriteBatchedStatements=true
    username: root
    password: 111111
    hikari:
      maximum-pool-size: 30
      connection-timeout: 3000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      "[hibernate.show_sql]": false
      "[hibernate.format_sql]": false
      "[hibernate.globally_quoted_identifiers]": true
      "[hibernate.jdbc.batch_size]": 50
      "[hibernate.order_inserts]": true
      "[hibernate.order_updates]": true
      "[hibernate.default_batch_fetch_size]": 50
      "[hibernate.query.in_clause_parameter_padding]": true
      "[hibernate.create_empty_composites.enabled]": true

  http:
    clients:
      connect-timeout: 20s
      read-timeout: 20s
    serviceclient:
      test:
        base-url: https://jsonplaceholder.typicode.com/todos
        read-timeout: 10s
        apiversion:
          default: 1.0
          insert:
            header: X-Version
